### ISSUE TITLE
Issue: Alpha Error

### ISSUE THREAD

**Issue by DontaeL** [Lumeo-Network/Terraform#22]
Issue with the DNS. Also issue with magic link

**Comment by denzuko** [comment]
Worked with @DontaeL earlier in the week. We got the DNS reset back to cloudflare and updated the sendgrid api token. Subscription button is working and email is being sent with the site being public again.

Improvements discovered:
  * Log aggregation and alerting from docker to NewRelic + PagerDuty
  * Automated Ticket creation on issues discovered
  * Automate DNS via terraform
  * Lock changes to DNS to only Terraform using both cloudflare and [namecheap](https://registry.terraform.io/providers/namecheap/namecheap/latest/docs) providers
  * Checkly tests for CMS

New stories will be created for the above improvements along with discussions for staffing on-call engineering support team.

**Comment by denzuko** [comment]
Further improvements:

  * Better issue reporting training for leadership and team members.
  * Template bug report [completed in .github repo so all new projects can have this template]
  * Backport template bug report and relate templates to all existing projects
